#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ken
#    username: root
#    password: root
#    #platform: mysql
#    #initialization-mode: always
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=ssicode
    username: sa
    password: P@55w0rd
    platform: mssql
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    database: SQL_SERVER
    show-sql: true
---
spring:
  datasource:
    url: jdbc:sqlserver://172.17.0.2:1433;database=ssicode
    username: sa
    password: P@55w0rd
    platform: mssql
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    database: SQL_SERVER
    show-sql: true
  profiles: prod
---
spring:
  datasource:
    url: jdbc:sqlserver://192.168.0.100:1433;database=ssicode
    username: sa
    password: P@55w0rd
    platform: mssql
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    database: SQL_SERVER
    show-sql: true
  profiles: home
---
spring:
  datasource:
    url: jdbc:sqlserver://mssql:1433;database=ssicode
    username: sa
    password: P@55w0rd
    platform: mssql
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    database: SQL_SERVER
    show-sql: true
  profiles: docker